import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { getPlatformSettings } from '@/lib/settings';
import ProceedToEventPaymentButton from '@/components/events/ProceedToEventPaymentButton';
import { applyEventCoupon } from './actions';

type Props={params:Promise<{id:string}>;searchParams?:Promise<{canceled?:string;coupon?:string}>};
export default async function EventPaymentPage({params,searchParams}:Props){
 const {id}=await params; const query=searchParams?await searchParams:{}; const supabase=await createClient(); const settings=await getPlatformSettings();
 const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/auth/login');
 const {data:event,error}=await supabase.from('events').select('id,name,slug,status,payment_status,is_paid,payment_override').eq('id',id).eq('owner_id',user.id).single(); if(error||!event)notFound();
 const {data:order}=await supabase.from('event_orders').select('*').eq('event_id',id).eq('user_id',user.id).eq('order_kind','event_initial').maybeSingle();
 const {data:items}=order?await supabase.from('event_order_items').select('*').eq('order_id',order.id).order('created_at'):{data:[] as any[]};
 if(!order) return <section className="mx-auto max-w-4xl px-4 py-10"><div className="rounded-3xl border border-yellow-500/20 bg-yellow-500/10 p-6 text-yellow-100"><h1 className="text-2xl font-black">Your event package needs to be rebuilt.</h1><p className="mt-2 text-sm">Open Enhance once so HypeKnight can create the itemized order record.</p><Link href={`/dashboard/events/${id}/edit/step-3`} className="mt-5 inline-flex rounded-2xl bg-yellow-100 px-5 py-3 font-black text-black">Open Enhance</Link></div></section>;
 const paid=order.status==='paid'||event.is_paid||event.payment_status==='paid'||event.payment_override||Number(order.total)<=0;
 return <section className="mx-auto max-w-5xl space-y-8 px-4 py-8 sm:px-6 lg:px-8">
  <Link href={`/dashboard/events/${id}/review`} className="text-sm text-white/60 hover:text-accent">← Back to Review</Link>
  <header className="rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-zinc-950 via-black to-zinc-900 p-6 sm:p-10"><p className="text-xs uppercase tracking-[.3em] text-accent">Secure Checkout</p><h1 className="mt-4 text-4xl font-black text-white sm:text-6xl">Complete your HypeKnight order.</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/65">See exactly what you are buying, apply a HypeKnight coupon before Stripe checkout, and keep a permanent receipt after payment.</p></header>
  {query.canceled?<Notice tone="yellow">Stripe checkout was canceled. Your order is still saved.</Notice>:null}{query.coupon==='applied'?<Notice tone="green">Coupon applied to this order.</Notice>:null}
  <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
   <section className="rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.25em] text-white/35">{order.order_number}</p><h2 className="mt-2 text-2xl font-black text-white">{event.name}</h2></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/60">{paid?'Paid':'Payment due'}</span></div><div className="mt-7 space-y-4">{(items||[]).map((item:any)=><div key={item.id} className="flex justify-between gap-5"><div><p className="font-bold text-white">{item.label}</p>{Number(item.quantity)>1?<p className="text-xs text-white/40">{item.quantity} × ${Number(item.unit_price).toFixed(2)}</p>:null}</div><p className="font-black text-white">${Number(item.line_total).toFixed(2)}</p></div>)}</div><div className="mt-7 border-t border-white/10 pt-5"><Row label="Subtotal" value={Number(order.subtotal)}/>{Number(order.discount_amount)>0?<Row label={`Coupon ${order.coupon_code||''}`} value={-Number(order.discount_amount)}/>:null}<div className="mt-4 flex items-center justify-between"><span className="text-lg font-black text-white">Total</span><span className="text-3xl font-black text-white">${Number(order.total).toFixed(2)}</span></div></div>{paid?<Link href={`/dashboard/receipts/${order.id}`} className="mt-7 block rounded-2xl bg-white px-5 py-4 text-center font-black text-black">View receipt</Link>:<div className="mt-7"><ProceedToEventPaymentButton eventId={id}/><p className="mt-3 text-center text-xs text-white/35">Payment is processed securely by Stripe.</p></div>}</section>
   <section className="rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8"><p className="text-xs uppercase tracking-[.25em] text-accent">Promo Code</p><h2 className="mt-2 text-2xl font-black text-white">Have a coupon?</h2>{settings.coupons_enabled===false?<p className="mt-4 text-sm text-white/50">Coupon entry is currently disabled by HypeKnight admin.</p>:<form action={applyEventCoupon} className="mt-6 space-y-4"><input type="hidden" name="event_id" value={id}/><input name="coupon_code" placeholder="Enter HypeKnight code" className="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-4 font-bold uppercase text-white outline-none focus:border-accent/50"/><button className="w-full rounded-2xl border border-white/10 px-5 py-4 font-black text-white hover:border-accent/50">Apply coupon</button></form>}<div className="mt-8 rounded-2xl border border-white/10 bg-black/20 p-5"><p className="font-bold text-white">After payment</p><p className="mt-2 text-sm leading-6 text-white/50">HypeKnight saves the order, Stripe payment reference, Stripe receipt link, and invoice PDF when Stripe provides them. You can return to Billing & Receipts later.</p></div></section>
  </div>
 </section>;
}
function Row({label,value}:{label:string;value:number}){return <div className="mt-2 flex justify-between text-sm"><span className="text-white/50">{label}</span><span className="text-white">{value<0?'-':''}${Math.abs(value).toFixed(2)}</span></div>}
function Notice({children,tone}:{children:React.ReactNode;tone:'yellow'|'green'}){return <div className={`rounded-2xl border p-4 ${tone==='green'?'border-green-500/20 bg-green-500/10 text-green-100':'border-yellow-500/20 bg-yellow-500/10 text-yellow-100'}`}>{children}</div>}
