'use client';

import { useMemo, useState } from 'react';

export type Addon = { code:string; name:string; description?:string|null; price:number; requires_event_end:boolean };

export default function EventEnhanceForm({ eventId, action, basePrice, includedDays, extraDayPrice, currentExtraDays, addons, hasExplicitEnd }: { eventId:string; action:(formData:FormData)=>void|Promise<void>; basePrice:number; includedDays:number; extraDayPrice:number; currentExtraDays:number; addons:Addon[]; hasExplicitEnd:boolean }) {
  const [extraDays, setExtraDays] = useState(currentExtraDays);
  const [selected, setSelected] = useState<string[]>([]);
  const liveSelected = addons.some((a) => selected.includes(a.code) && a.requires_event_end);
  const total = useMemo(() => extraDays * extraDayPrice + addons.filter((a) => selected.includes(a.code)).reduce((s,a) => s + a.price,0), [extraDays, extraDayPrice, addons, selected]);
  function toggle(code:string) { setSelected((v) => v.includes(code) ? v.filter((x) => x !== code) : [...v, code]); }
  return <form action={action} className="space-y-6"><input type="hidden" name="event_id" value={eventId} />
    <section className="rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8"><h2 className="text-2xl font-black text-white">Included Discovery</h2><p className="mt-2 text-sm text-white/50">{includedDays} Discovery days before your event are included free.</p><div className="mt-6 flex items-center justify-between rounded-2xl border border-white/10 bg-black/20 p-4"><div><p className="font-bold text-white">Extended Discovery days</p><p className="text-sm text-white/45">${extraDayPrice.toFixed(2)} each</p></div><input name="extra_promo_days" type="number" min="0" value={extraDays} onChange={(e) => setExtraDays(Math.max(0, Number(e.target.value)||0))} className="w-24 rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-right text-white" /></div></section>
    <section className="rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8"><h2 className="text-2xl font-black text-white">Enhance the event</h2><p className="mt-2 text-sm text-white/50">Only products enabled by HypeKnight admin appear here.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{addons.length ? addons.map((addon) => <label key={addon.code} className="cursor-pointer rounded-2xl border border-white/10 bg-black/20 p-5 has-[:checked]:border-accent/60 has-[:checked]:bg-accent/10"><div className="flex items-start gap-3"><input type="checkbox" name="product_code" value={addon.code} checked={selected.includes(addon.code)} onChange={() => toggle(addon.code)} className="mt-1" /><div><p className="font-black text-white">{addon.name}</p><p className="mt-1 text-sm leading-6 text-white/50">{addon.description}</p><p className="mt-3 font-black text-accent">${addon.price.toFixed(2)}</p>{addon.requires_event_end ? <p className="mt-2 text-xs text-white/40">Runs live through the event end time.</p> : null}</div></div></label>) : <div className="md:col-span-2 rounded-2xl border border-white/10 p-5 text-sm text-white/50">No live add-ons are currently enabled. Patron Pulse and Linkd’N can be activated later from Admin Commerce.</div>}</div></section>
    {liveSelected && !hasExplicitEnd ? <section className="rounded-[2rem] border border-yellow-500/20 bg-yellow-500/10 p-6"><h2 className="text-xl font-black text-yellow-100">Live product requires an end time</h2><p className="mt-2 text-sm text-yellow-100/70">HypeKnight keeps this event discoverable while live sensors, pulses, or Linkd’N experiences are operating.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="text-sm font-bold text-yellow-100">End date *</span><input name="live_end_date" type="date" required className="mt-2 w-full rounded-xl border border-yellow-500/20 bg-black/30 px-4 py-3 text-white" /></label><label><span className="text-sm font-bold text-yellow-100">End time *</span><input name="live_end_time" type="time" required className="mt-2 w-full rounded-xl border border-yellow-500/20 bg-black/30 px-4 py-3 text-white" /></label></div></section> : null}
    <section className="rounded-[2rem] border border-accent/20 bg-accent/5 p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-white/50">Current order estimate</p><p className="mt-2 text-4xl font-black text-white">${total.toFixed(2)}</p></div><button className="rounded-2xl bg-accent px-6 py-4 font-black text-black">Continue to Review →</button></div></section>
  </form>;
}
