import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function BillingPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/auth/login');
 const {data:orders,error}=await supabase.from('event_orders').select('id,order_number,status,total,coupon_code,paid_at,created_at,stripe_receipt_url,stripe_invoice_pdf,event:events(id,name,slug)').eq('user_id',user.id).order('created_at',{ascending:false}); if(error)throw new Error(error.message);
 const totalPaid=(orders||[]).filter((o:any)=>o.status==='paid').reduce((sum:number,o:any)=>sum+Number(o.total||0),0);
 return <section className="mx-auto max-w-6xl space-y-8 px-4 py-8 sm:px-6 lg:px-8"><Link href="/dashboard" className="text-sm text-white/60 hover:text-accent">← Dashboard</Link><header className="rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-zinc-950 via-black to-zinc-900 p-6 sm:p-10"><p className="text-xs uppercase tracking-[.3em] text-accent">Billing & Receipts</p><h1 className="mt-4 text-4xl font-black text-white sm:text-6xl">Your HypeKnight purchases.</h1><p className="mt-4 text-white/60">Itemized HypeKnight orders plus Stripe receipt and invoice links.</p><p className="mt-6 text-3xl font-black text-white">${totalPaid.toFixed(2)} <span className="text-sm font-normal text-white/40">paid</span></p></header><div className="space-y-4">{(orders||[]).length?(orders||[]).map((order:any)=><article key={order.id} className="rounded-[2rem] border border-white/10 bg-white/5 p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-white/35">{order.order_number}</p><h2 className="mt-2 text-xl font-black text-white">{order.event?.name||'Event order'}</h2><p className="mt-1 text-sm text-white/45">{order.paid_at?new Date(order.paid_at).toLocaleString():new Date(order.created_at).toLocaleDateString()} · {order.status}{order.coupon_code?` · ${order.coupon_code}`:''}</p></div><div className="flex items-center gap-3"><p className="text-2xl font-black text-white">${Number(order.total).toFixed(2)}</p><Link href={`/dashboard/receipts/${order.id}`} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold text-white">Receipt</Link></div></div></article>):<div className="rounded-3xl border border-white/10 bg-white/5 p-8 text-white/50">No V3.4 orders yet. Existing legacy payments remain available in the current payment history.</div>}</div></section>;
}
