import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { getPlatformSettings } from '@/lib/settings';
import { updateCommerceSettings, updateProduct } from './actions';

type Props={searchParams?:Promise<{saved?:string}>};
export default async function AdminCommercePage({searchParams}:Props){const query=searchParams?await searchParams:{};const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login');const {data:profile}=await supabase.from('profiles').select('app_role').eq('id',user.id).single();if(profile?.app_role!=='admin')redirect('/dashboard');const settings=await getPlatformSettings();const {data:products,error}=await supabase.from('platform_products').select('*').order('sort_order');if(error)throw new Error(error.message);
 return <section className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6 lg:px-8"><Link href="/admin" className="text-sm text-white/60 hover:text-accent">← Admin Control Center</Link><header className="rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-zinc-950 via-black to-zinc-900 p-8"><p className="text-xs uppercase tracking-[.3em] text-accent">Commerce Control</p><h1 className="mt-3 text-4xl font-black text-white sm:text-6xl">Event Builder & Products</h1><p className="mt-4 max-w-3xl text-white/60">Control venue matching, default discovery timing, coupons, receipts, and which LEI event products are available in the builder.</p></header>{query.saved?<div className="rounded-2xl border border-green-500/20 bg-green-500/10 p-4 text-green-100">Commerce settings saved.</div>:null}
 <form action={updateCommerceSettings} className="rounded-[2rem] border border-white/10 bg-white/5 p-6 sm:p-8"><h2 className="text-2xl font-black text-white">Builder controls</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><Toggle name="event_builder_enabled" label="Enable V3.4 Event Builder" checked={settings.event_builder_enabled??true}/><Toggle name="venue_matching_enabled" label="Match venues by physical address" checked={settings.venue_matching_enabled??true}/><Toggle name="venue_approval_required" label="Require venue-owner approval" checked={settings.venue_approval_required??true}/><Toggle name="coupons_enabled" label="Enable HypeKnight coupons" checked={settings.coupons_enabled??true}/><Toggle name="commerce_receipts_enabled" label="Enable Billing & Receipts" checked={settings.commerce_receipts_enabled??true}/><label><span className="text-sm font-bold text-white/70">Default discovery buffer (minutes)</span><input name="default_discovery_buffer_minutes" type="number" min="1" defaultValue={settings.default_discovery_buffer_minutes??30} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white"/></label></div><button className="mt-6 rounded-2xl bg-accent px-6 py-4 font-black text-black">Save builder controls</button></form>
 <section className="space-y-4"><div><p className="text-xs uppercase tracking-[.25em] text-accent">Product Catalog</p><h2 className="mt-2 text-3xl font-black text-white">Event add-ons</h2></div>{(products||[]).map((p:any)=><form action={updateProduct} key={p.id} className="rounded-[2rem] border border-white/10 bg-white/5 p-6"><input type="hidden" name="product_id" value={p.id}/><div className="grid gap-5 lg:grid-cols-[1fr_180px_220px]"><div><p className="text-xs uppercase tracking-[.2em] text-white/35">{p.code} · {p.product_family}</p><h3 className="mt-2 text-2xl font-black text-white">{p.name}</h3><textarea name="description" rows={2} defaultValue={p.description||''} className="mt-4 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white"/></div><label><span className="text-sm font-bold text-white/70">Price</span><input name="price" type="number" step="0.01" min="0" defaultValue={Number(p.price||0)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white"/></label><div className="space-y-3"><Toggle name="enabled" label="Available in builder" checked={p.enabled}/><Toggle name="requires_event_end" label="Requires live event end" checked={p.requires_event_end}/><button className="w-full rounded-2xl border border-white/10 px-4 py-3 font-black text-white">Save product</button></div></div></form>)}</section></section>;
}
function Toggle({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/20 p-4"><span className="font-bold text-white">{label}</span><input name={name} type="checkbox" defaultChecked={checked} className="h-5 w-5"/></label>}
