import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { approveVenueConnection, declineVenueConnection } from './actions';
export default async function VenueConnectionsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login');
 const {data:requests,error}=await supabase.from('venue_event_connection_requests').select('id,status,created_at,event:events(id,name,venue_name,address,city,state,event_start_at),venue:venues(id,name,address,city,state)').eq('venue_owner_id',user.id).order('created_at',{ascending:false});if(error)throw new Error(error.message);
 return <section className="mx-auto max-w-6xl space-y-8 px-4 py-8 sm:px-6 lg:px-8"><Link href="/dashboard/venues" className="text-sm text-white/60 hover:text-accent">← My Venues</Link><header className="rounded-[2.5rem] border border-white/10 bg-white/5 p-8"><p className="text-xs uppercase tracking-[.3em] text-accent">Venue Permissions</p><h1 className="mt-3 text-4xl font-black text-white">Event connection requests</h1><p className="mt-3 text-white/55">An address match never gives a promoter control of your venue. You decide whether the HypeKnight event may connect to your venue account.</p></header><div className="space-y-4">{(requests||[]).length?(requests||[]).map((r:any)=><article key={r.id} className="rounded-[2rem] border border-white/10 bg-white/5 p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-white/35">{r.status}</p><h2 className="mt-2 text-2xl font-black text-white">{r.event?.name}</h2><p className="mt-2 text-sm text-white/55">Requested venue: {r.venue?.name}<br/>{r.event?.address}, {r.event?.city}, {r.event?.state}</p></div>{r.status==='pending'?<div className="flex gap-3"><form action={declineVenueConnection}><input type="hidden" name="request_id" value={r.id}/><button className="rounded-xl border border-white/10 px-4 py-3 font-bold text-white">Decline</button></form><form action={approveVenueConnection}><input type="hidden" name="request_id" value={r.id}/><button className="rounded-xl bg-accent px-4 py-3 font-black text-black">Approve connection</button></form></div>:null}</div></article>):<div className="rounded-3xl border border-white/10 bg-white/5 p-8 text-white/50">No venue connection requests.</div>}</div></section>;
}
